handler: src/commands/addProperty.handler
events:
  - http:
      path: property
      method: post
      cors: true
      # authorizer:
      #   arn: ${self:custom.authorizerARN}
      #   resultTtlInSeconds: 0
      #   identitySource: method.request.header.Authorization
      #   type: token
      request:
        schemas:
          application/json: ${file(schemas/addProperty.json)}
