handler: src/commands/getProperty.handler
events:
  - http:
      path: property/{id}
      method: get
      cors: true
      # authorizer:
      #   arn: ${self:custom.authorizerARN}
      #   resultTtlInSeconds: 0
      #   identitySource: method.request.header.Authorization
      #   type: token
