handler: src/commands/simpleGet.handler
events:
  - http:
      path: simpleGet
      method: get
      cors: true
      # authorizer:
        # arn: ${self:custom.authorizerARN}
        # resultTtlInSeconds: 0
        # identitySource: method.request.header.Authorization
        # type: token
